name: Build And Test Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Test My Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Uncomment the following section if you want to cache Gradle packages
      # - name: Cache Gradle packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.gradle/caches
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew
        
      - name: Unit Tests
        working-directory: ./backend
        run: ./gradlew test

      - name: Build the application
        working-directory: ./backend
        run: ./gradlew
